### PR TITLE
fix: variable scopes with let and assign

### LINKED ISSUE #129: Assigned value is discarded when exiting an inner scope
```
ask {
    let a = 2

    let c = 'Hello'
    
    if(a < 5) {
        c = '!'
    }
    
    return c
}
```
returns `Hello`
instead of `!`

### PR DESCRIPTION
**Pull request by mhagmajer**
Closes #129

### CODE REVIEW

**Comment by YonatanKra** [comment]
Darn - I was in the middle of solving it ;)
I'll go over it during the evening.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer, let me check it within an hour.

File: src/askjsx/lib/Let.tsx [hunk 1]
```diff
@@ -3,13 +3,18 @@ import * as askjsx from './jsx';
 import { AskCodeOrValue } from '../../askcode';
 askjsx;
 
-export function Set({
-  name,
-  value,
-}: {
+type Props = {
   name: string;
   type?: string;
```
Comment (YonatanKra) [inline src/askjsx/lib/Let.tsx:8]: What is the "type" here?

File: src/askjsx/lib/Let.tsx [hunk 2]
```diff
@@ -20,12 +25,13 @@ export function Set({
   );
 
   return (
-    <code let>
+    <code {...{ [code]: true }}>
```
Comment (YonatanKra) [inline src/askjsx/lib/Let.tsx:28]: if code is just a string, isn't it enough to just print it here?

File: src/askvm/resources/core/let.ts [hunk 3]
```diff
@@ -16,6 +16,21 @@ export const letRes = resource({
       throw new Error(`Key "resources" cannot be redeclared`);
     }
 
+    if (code.name === 'assign') {
+      for (
```
Comment (YonatanKra) [inline src/askvm/resources/core/let.ts:20]: It looks like you want to go into the prototype chain here. Are the values deep inside? In what case you'll have to search the values deeper than the first prototype?

**Comment by YonatanKra** [comment]
Side note: reviewing this clearly shows we need to remove the auto-generated files from git. They are such a clatter... really hard to go over the PR.
Is that a thing? #170

File: src/askvm/resources/core/let.ts [hunk 4]
```diff
@@ -1,4 +1,4 @@
-import { any, resource, run, runUntyped } from '../../lib';
+import { any, resource, run, runUntyped, Options } from '../../lib';
 
 export const letRes = resource({
```
Comment (YonatanKra) [inline src/askvm/resources/core/let.ts:3]: Can we give it a clearer name? Does `letRes` stand for `Let Resolve`?

File: src/askscript/__tests__/90-misc/scope-02.test.ts [hunk 5]
```diff
@@ -0,0 +1,7 @@
+import program from './scope-02.ask';
```
Comment (YonatanKra) [inline src/askscript/__tests__/90-misc/scope-02.test.ts:1]: Why not have one test file for `let` and add all the possibilities there explicitly? 
It seems to me it is harder to maintain and much harder to understand the tests as they are now.
All in all, there are 2-3 scenarios per core functionality and it would be much easier to understand and follow if it were set in one file.
Something like:
```
import simpleAssign from './basics17-assign.ask';
import scopedAssign from './basics17-assign-scoped.ask';
import emptyAssign from './basics17-assign-empty.ask';

test('assign value for declared variable', async () => {
  await expect(await simpleAssign()).toEqual(2);
});

test('assign value inside scope for globally declared variable', async () => {
  await expect(await scopedAssign()).toEqual(2);
});

test('throw an error when assign to undeclared variable', async () => {
  await expect(emptyAssign()).rejects.toThrow();
});
```
@mhagmajer @czerwinskilukasz1 
What do you think?

File: src/askjsx/lib/Let.tsx (hunk 1 above)
Comment (mhagmajer) [reply src/askjsx/lib/Let.tsx:8]: in `let n: int = 5` it's the value of `int`

File: src/askjsx/lib/Let.tsx (hunk 2 above)
Comment (mhagmajer) [reply src/askjsx/lib/Let.tsx:28]: I don't knowa shorter way to add a new dynamic property in JSX tag

File: src/askvm/resources/core/let.ts (hunk 3 above)
Comment (mhagmajer) [reply src/askvm/resources/core/let.ts:20]: If you are in a child scope (eg. inside the curly braces of an if block), your assignment should only affect the variable from your closest parent scope

File: src/askvm/resources/core/let.ts (hunk 4 above)
Comment (mhagmajer) [reply src/askvm/resources/core/let.ts:3]: `letRes` actually stand for let resource. This pattern is used in other places as well. If we were to change it, let's make this a matter of another issue/PR.

File: src/askscript/__tests__/90-misc/scope-02.test.ts (hunk 5 above)
Comment (mhagmajer) [reply src/askscript/__tests__/90-misc/scope-02.test.ts:1]: This is important and general subject. Let's take it into another issue. I also think that testing is very important and we should reconsider our approach here.

**Comment by mhagmajer** [comment]
>Side note: reviewing this clearly shows we need to remove the auto-generated files from git. They are such a clatter... really hard to go over the PR.
Is that a thing? #170

Yes, @YonatanKra, this is being considered and we can discuss it further in its issue. Perhaps we don't need to keep parsing snapshots for all .ask files

File: src/askscript/__tests__/90-misc/scope-02.test.ts (hunk 5 above)
Comment (czerwinskilukasz1) [reply src/askscript/__tests__/90-misc/scope-02.test.ts:1]: https://github.com/xFAANG/askql/issues/249
